// <auto-generated />
namespace freelunch.uk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lunchkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lunchkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201607070743225_lunch-key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
